### ISSUE TITLE
screenshots

### ISSUE THREAD

**Issue by aleivag** [mikeckennedy/pyramid-web-builder-python-gui#1]
There is this great podcast called "python bytes" :wink: that once said that you should always include screenshots with you gui... 
:smiley:

**Comment by mikeckennedy** [comment]
LOL, thanks @aleivag Agreed. I actually ran into a bug with Gooey intersected with PyInstaller over here:

https://github.com/chriskiehl/Gooey/issues/252

And didn't get this repo fully finished the way I wanted. I'll do a proper blog post (next week?) and it will have plenty of screenshots! ;)
